#!/bin/sh
case $* in
    "--help")
        echo "'gg' restarts the system. Use 'gg no re' to halt the system instead.";;
    "")
        sudo systemctl reboot;;
    "nore"|"no re")
        sudo systemctl poweroff;;
    *)
        echo "yeah $* gg";;
esac
